# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

kotlin.code.style=official
kotlin.incremental=true

# Suppress noisy build warnings about target/source 1.8
android.suppressUnsupportedCompileSdk=35
